### ISSUE TITLE
Messdaten Strings gesamt Wert kwh wird nicht für den Export / Exporteinstellungen in der Auswahl angeboten.

### ISSUE THREAD

**Issue by smartboart** [rxhan/RSCPGui#12]
Messdaten Strings gesamt Wert kw/h wird nicht für den Export / ExorteinstellungenAuswahl angeboten.
![grafik](https://user-images.githubusercontent.com/38385805/111890164-32f06c80-89e7-11eb-90da-ec392f7645c6.png)

**Comment by rxhan** [comment]
Aktuell werden nur ermittelte Werte zur Verfügung gestellt, keine berechneten Werte. Die Gesamtenergie ist einer der berechneten Werte.

**Comment by smartboart** [comment]
ok, keine Problem, den Gesamtwert kann mann dann auch mit nem kleinen Script selber addieren.
