### ISSUE TITLE
Direkte Verbindung liefert Daten nicht vollständig / Keine Daten im Tab Wechselrichter

### ISSUE THREAD

**Issue by mccrossen** [rxhan/RSCPGui#16]
In der Version pre10 wird bei meinem System keine Wechselrichter angezeigt. Mit der Version pre9 funktioniert es noch.
Es sieht dann so aus:
![grafik](https://user-images.githubusercontent.com/31479918/114135640-cf809d00-9909-11eb-985f-912c55854b51.png)
Anbei auch das Logfile:
[rscpgui.log](https://github.com/rxhan/RSCPGui/files/6283470/rscpgui.log)

Es wurde mit der Zip-Variante unter Windows 10 ausprobiert.

Werden noch weitere Informationen benötigt?

**Comment by rxhan** [comment]
Danke für die Information, mir ist schon seit längerem aufgefallen, dass es Timingprobleme beim Abfragen aufwendigerer Daten über die direkte Verbindung gibt. Konkret sieht das so aus, dass die Daten nicht vollständig übertragen werden und dadurch nicht richtig entschlüsselt werden können. (Siehe letzte Einträge in deiner Logdatei). Das das jetzt mit pre10 und nicht mit pre9 auftaucht wundert mich zwar etwas, da in diesem Bereich nichts geändert wurde, kann aber auch Zufall sein.

Was mich interessieren würde:

Ist das reproduzierbar? Wenn du z.B. mehrfach auf aktualisieren klickst.
Und: tritt das Problem auch auf, wenn die web-Verbindung statt der direkten Verbindung verwendet wird?
Hast du mehrere Wechselrichter am E3/DC?

**Comment by mccrossen** [comment]
> Ist das reproduzierbar? Wenn du z.B. mehrfach auf aktualisieren klickst.
Es scheint wirklich ein erstaunlicher Zufall im pre10 gewesen zu sein. Habe es jetzt nach vielen probieren geschafft über Aktualisieren sowohl Daten angezeigt zu bekommen, als auch das wieder alles leer ist, beides jetzt auch mit dem pre9. Das Problem kommt bei mir jetzt auch im Reiter Batterien zum Vorschein:
![grafik](https://user-images.githubusercontent.com/31479918/114166786-75460300-992e-11eb-9b44-45631262cbd6.png)

**Workaround: Manuell alle drei Sekunden aktualisieren bis Daten angezeigt werden.** 

>  Und: tritt das Problem auch auf, wenn die web-Verbindung statt der direkten Verbindung verwendet wird?
Ich verwende ausschließlich direkt, da Web irgendwie bei mir nie sauber funktionierte.

>  Hast du mehrere Wechselrichter am E3/DC?
Ich habe nur einen E3DC mit seinem einen interen Wechselrichter und drei Batterien

**Comment by rxhan** [comment]
Ich hab mal etwas herumgetestet, es wird daran liegen, dass E3DC die Daten nicht schnell genug liefert. Da läuft dann der Puffer leer und das Programm denkt der Empfang ist abgeschlossen und arbeitet weiter. Interessanterweise entsprichen die empfangenen Daten einem vielfachen der MTU-Nutzdaten von 1460 Bytes. Ich werde heute Abend nochmal testen, aber außer hochsetzen einer Wartezeit fällt mir aktuell noch nichts ein. Die Wartezeit verlangsamt jedoch die Geschwindigkeit der Abfragen, daher versuche ich die Abfragehäufigkeit zu erhöhen, dies führt jedoch am Ende wieder zum selben Problem, - Aufwendige Abfragen dauern und der Puffer kann leerlaufen.

**Comment by rxhan** [comment]
Ich habe ein paar Anpassungen gemacht zumindest bei mir laufen die Abfragen bislang zuverlässig. Das ist direkt im Master brancht hochgeladen.  Commit 15bb4b0936197997fb9e76959141b60a3b68d2aa
