### ISSUE TITLE
SSL Fehler, keine Übertragung/Abrufen der Daten des Portals

### ISSUE THREAD

**Issue by elMontair** [rxhan/RSCPGui#20]
Keine Übertragung/Abruf der Daten aus dem Portal (Vergleiche mit anderen E3DCs) aufgrund eines SSL Fehlers laut Log.

**Comment by rxhan** [comment]
Das Problem sollte nun behoben sein, dass Zertifikat war abgelaufen.

**Comment by elMontair** [comment]
Danke!Ansonsten super Software. Danke dafür.Am 07.08.21 um 18:08 schrieb rxhan
                
            
            
                
                    Von: "rxhan" ***@***.***>Datum: 7. August 2021An: "rxhan/RSCPGui" ***@***.***>Cc: "elMontair" ***@***.***>,"Author" ***@***.***>Betreff: Re: [rxhan/RSCPGui] SSL Fehler, keine Übertragung/Abrufen der Daten des Portals (#20)
                
                
Das Problem sollte nun behoben sein, dass Zertifikat war abgelaufen.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/rxhan/RSCPGui/issues/20#issuecomment-894673437",
"url": "https://github.com/rxhan/RSCPGui/issues/20#issuecomment-894673437",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
