### ISSUE TITLE
MQTT in pre10 ohne Funktion?

### ISSUE THREAD

**Issue by Brovning** [rxhan/RSCPGui#21]
Hallo,

habe in meiner Windows VM die Version pre10 eingerichtet.

Die Werte vom Speicher gehen ein, jedoch erhalte ich bspw. im MQTT Explorer keine Werte.

Config von E3DC RSCPGui sieht wie folgt aus:
![image](https://user-images.githubusercontent.com/39644775/130360629-f12395da-9a4d-4ed8-9b0c-7108c7a0f137.png)

Config vom MQTT Explorer sieht wie folgt aus:
![image](https://user-images.githubusercontent.com/39644775/130360641-b2acb505-0b83-43e4-81f6-8a87ca18db11.png)

Ich erhalte  im MQTT Explorer immer die Fehlermeldung "Disconnected from Server" und in meiner Hausautomatisierung "Connection actively refused by Server".

Ist hier aktuell ein Fehler bekannt?
Oder ist meine Konfiguration fehlerhaft?

Mein Verständnis:
RSCPGui erstellt einen MQTT Server und ich kann mich auf diesen mit einem MQTT Client verbinden, sobald ich den Haken in "MQTT" gesetzt habe und auf "Einstellungen speichern" geklickt habe.
Habe ich hier etwas übersehen?

Vielen Dank im Voraus!

Gruß

Jürgen

**Comment by rxhan** [comment]
Hallo Jürgen,

du hast da leider etwas falsch verstanden. RSCPGui erstellt keinen MQTT Server (Broker) sondern erwartet einen und verbindet sich damit als Client. Du musst also irgendwo schon einen Broker installiert haben, damit du die Daten dorthin pushen kannst.

MfG, Hannes
