### ISSUE TITLE
ValueError: 117440511 is not a valid RSCPTag - Websocket-Verbindung nicht möglich

### ISSUE THREAD

**Issue by flexerl** [rxhan/RSCPGui#22]
Ich bekomme die pre10 leider nicht zum Laufen, und alle anderen Versionen, die früher funktionierten, wollen auch nicht mehr, denn dort kommt jetzt die selbe Meldung. Im Log steht ausschließlich 

> 2021-09-08 18:18:56,059 - e3dcwebgui - ERROR - ConID: 1631117832.68 - Fehler beim Verarbeiten der Daten : 117440511 is not a valid RSCPTag
> Traceback (most recent call last):
>   File "e3dcwebgui.py", line 279, in on_message
>   File "e3dc\_rscp_utils.py", line 108, in decode_server_data
>   File "e3dc\_rscp_utils.py", line 124, in decode_data
>   File "e3dc\_rscp_utils.py", line 152, in decode_data
>   File "e3dc\_rscp_utils.py", line 129, in decode_data
>   File "C:\Users\Johannes\AppData\Local\Programs\Python\Python38\lib\enum.py", line 315, in __call__
>   File "C:\Users\Johannes\AppData\Local\Programs\Python\Python38\lib\enum.py", line 617, in __new__
> ValueError: 117440511 is not a valid RSCPTag

Auch 9 scheint kein valider Tag zu sein. 

In einem anderen Issue meinte jemand, er hätte das RSCP-Passwort neu gesetzt und alles würde funktionieren. Ich kann in RSCP-GUI kein RSCP-Passwort setzen, nur das bestehende überschreiben?! Egal was ich tue oder eingebe, es hagelt nur Fehler, und leider komme ich an der Stelle nicht weiter. Das RSCP-Passwort scheint zu stimmen, denn die Software E3DC-Control kann sich einwandfrei mit dem S10 verbinden. Was mache ich noch falsch? Bitte um Hilfestellung.

**Comment by flexerl** [comment]
Kurzes Update: Ich habe nun die Software auf einer Windows10-VM installiert, welche im selben Subnetz ist wie das S10. Ich habe die Daten erneut eingegeben und konnte mich erfolgreich verbinden. Die Meldungen im Log haben anscheinend nichts mit dem Problem zu tun, und selbiges schiebe ich auf ein Routingproblem meinerseits - obwohl es vorher ja auch problemlos aus einem anderen Subnetz heraus ging.

**Comment by rxhan** [comment]
Hallo, ich denke es könnte an einem Problem mit den Websockets liegen. Die Verbindungsart scheint aktuell gar nicht zu funktionieren. Ich konnte mich um das Problem leider noch nicht kümmern.

**Comment by rxhan** [comment]
Habe das Problem jetzt doch lokalisiert, im aktuellen Master Repository sollte es behoben sein, zumindest bei mir funktioniert die Verbindung wieder problemlos.
