### ISSUE TITLE
Keine Anzeige der Wechselrichterdaten (Phasen/Strings/Temperaturen)

### ISSUE THREAD

**Issue by universal-dilettant** [rxhan/RSCPGui#33]
Hi,
wie im Subject beschrieben. 
https://pv.pincrushers.de/rscpgui/1676103379_98027e156a0de54c34691ca76819056e.json gerade hochgeladen. Kannst du dir vllt bei Gelegenheit mal anschauen.
Dei dropdown Box links oben ist und bleibt leer.
Danke

<img width="824" alt="Screenshot 2023-02-11 092327" src="https://user-images.githubusercontent.com/123087960/218248284-c9b2bf9c-6c9a-4aec-8c7f-f081f90c76e5.png">

**Comment by rxhan** [comment]
Danke für den Hinweis, ich habe mir die Daten angesehen. Die PVI-Daten weichen etwas von dem ab, wie sie sein sollten. 
Was sagt die rscpgui.log ? Müsste eigentlich ein entsprechender Fehler enthalten sein.

**Comment by universal-dilettant** [comment]
Ja, folgende relevanten Einträge:

`2023-02-22 09:37:11,228 - rscpguiframe - ERROR - Fehler beim Abruf der PVI-Daten`
`Traceback (most recent call last):`
`  File "rscpguiframe.py", line 359, in updateTab`
`  File "rscpguiframe.py", line 1020, in fill_pvi`
`  File "rscpguiframe.py", line 1049, in fill_pvi_index`
`  File "e3dc\_rscp_dto.py", line 105, in __getitem__`
`AttributeError`

**Comment by rxhan** [comment]
Ich hab für das Problem mal einen neuen Branch eröffnet in dem wir testen können: "https://github.com/rxhan/RSCPGui/tree/Issue_(%2333)" bitte mal damit testen.

Ansonsten:
Bekommst du die Batteriedaten angezeigt? 

Du kannst das Loglevel mit -v INFO oder -v DEBUG erhöhen. Dann wird aber sehr viel protokolliert, vielleicht hilft das. Auch die Zugangsdaten! -> also vorsichtig beim Kopieren.

**Comment by universal-dilettant** [comment]
Ich bin kein python Experte, das vorneweg.
Ich habe mir python 3.9.13 unter Windows installiert, das Repo lokal geclont, die requirements installiert / compiliert, das rscpe3dc.conf.ini file aus der Originalversion rüberkopiert und .\main.py gestartet.
Bei "aktualisieren" der Einstellungen kam folgender Fehler auf der Py-Console:

Traceback (most recent call last):
  File "C:\Users\xxx\Documents\GitHub\RSCPGui\e3dc\_rscp_utils.py", line 73, in encode_data
    res = struct.pack(pack_format, rscp_dto.tag.value, rscp_dto.type.value, data_length, rscp_dto.data)
struct.error: required argument is not an integer

**Comment by rxhan** [comment]
Sieht ja gut aus, die Vorgehensweise ist auch richtig so. Welchen Branch hast du geklont?

**Comment by universal-dilettant** [comment]
Issue_(#33)

**Comment by rxhan** [comment]
Alles klar, danke habe es in den Master übernommen.

**Comment by universal-dilettant** [comment]
Ich und die Community haben dir zu danken 😊
