### ISSUE TITLE
Kein Abruf von Daten des Wechselrichters nach Update 2023_022 möglich

### ISSUE THREAD

**Issue by elMontair** [rxhan/RSCPGui#37]
Seit dem Update des E3DC S10 E Pro auf 2023_022 können mit der aktuellen Version keine Daten des WR auf dem Reiter "Wechselrichter" mehr ausgelesen werden. Momentanleistungswerte unter "E3DC, Basis" sowie auf dem Reiter "Leistungsmesser" werden weiterhin angezeigt.

Evtl. haben sich die Register geändert?

**Comment by rxhan** [comment]
Hatte der Abruf mit 2023_02 noch funktioniert?

**Comment by elMontair** [comment]
Ich bin direkt von 2022_046 geupdated worden. Kann ich also nicht beantworten.

**Comment by elMontair** [comment]
Inzwischen gibt es 2023_024. Leider sind noch immer alle Daten im Reiter Wechselrichter leer. Vorher konnte ich ohne Probleme die aktuellen Leistungsdaten abrufen. Andere Daten wie Leistungsmesser, Batterien, DCDC Wandler sowie unter E3DC auch die aktuelle Leistung gehen nach wie vor zu 100%.

Konntest du das verifizieren?

**Comment by Matis-11** [comment]
Mit js 5.0.8 kommen auch einige Fehler in regelmäßigen Abständen:
![grafik](https://github.com/rxhan/RSCPGui/assets/80908396/02a6e855-268d-426d-9f8d-752d1722ff4f)

**Comment by rxhan** [comment]
Habe das Problem bereits länger gelöst, aber den Branch nicht aktualisiert. Habe nun neben weiteren Fehlerbehebungen den Master-Branch aktualisiert. Bitte mal mit dem aktuellen Stand testen.
Ursache: Einige Tags werden nicht mehr übermittelt, jedoch im Programm nicht abgefangen.

**Comment by elMontair** [comment]
Kannst du die Windows Binary ebenfalls aktualisieren?

**Comment by rxhan** [comment]
Sorry für die späte Rückmeldung, habe sie erstellt:
https://github.com/rxhan/RSCPGui/releases/tag/pre12
