### ISSUE TITLE
Kann die datei RSCPGui.exe nicht finden?

### ISSUE THREAD

**Issue by mibr85** [rxhan/RSCPGui#41]
In der readme wird beschrieben: Keine Installation notwendig, die Binary (RSCPGui.exe) kann direkt ausgeführt werden.

**Comment by rxhan** [comment]
Du findest die Dateien in den Releases: https://github.com/rxhan/RSCPGui/releases wenn du auf Assets klickst. Wenn du ein H20 hast, nimm die Test-Version ansonsten ist das Pre12 ok.
