### ISSUE TITLE
Starten unter ubuntu 20.04

### ISSUE THREAD

**Issue by msei99** [rxhan/RSCPGui#5]
Ich versuche das Programm unter ubuntu 20.04 mit Python 3.8.5 zu starten.

Aufruf mit "python3 main.py"

Dann passiert aber gar nix, das Programm beendet sich einfach wieder.

Die ganzen requirements sind installiert.

Wo muss man eigentlich Ziel, User, PW eingeben?

**Comment by rxhan** [comment]
Die Konfiguration kann nur über die Oberfläche gemacht werden.
Starte mal mittels -v DEBUG -l dann sollte mehr Protokolliert werden.
Mit -h bekommst du eine Übersicht aller Konsolenparameter.

**Comment by msei99** [comment]
OK, es sieht so aus als ob wxPython nicht vorhanden ist.
2020-11-19 18:03:58,921 - __main__ - DEBUG - Programmstart
2020-11-19 18:03:58,926 - __main__ - WARNING - wxPython steht nicht zur Verfügung, Programm beschränkt sich auf die Console
2020-11-19 18:03:58,926 - __main__ - INFO - Lade Module
2020-11-19 18:03:59,298 - __main__ - INFO - Module geladen, initialisiere Console
2020-11-19 18:03:59,299 - rscpguimain - INFO - Main initialisiert
2020-11-19 18:03:59,299 - rscpguiconsole - DEBUG - Nichts zu tun, versuche -h
2020-11-19 18:03:59,299 - __main__ - INFO - Programm beendet

Komisch das wxPython nicht installiert sein soll.
Eigentlich habe ich es installiert:

pip3 install wxPython
Requirement already satisfied: wxPython in /home/mani/.local/lib/python3.8/site-packages (4.1.0)
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from wxPython) (7.0.0)
Requirement already satisfied: numpy; python_version >= "3.0" in /home/mani/.local/lib/python3.8/site-packages (from wxPython) (1.19.4)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from wxPython) (1.14.0)

**Comment by msei99** [comment]
Bin ein Stück weiter, musste noch etwas nachinstallieren. Jetzt startet das GUI. Ich teste dann mal weiter.

sudo apt-get install git curl libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0

hat geholfen.

**Comment by rxhan** [comment]
Fein, danke für dei Rückmeldung. Falls noch etwas auffällt, gerne melden.
