### ISSUE TITLE
Update Ladeeinstellungen AttributeError

### ISSUE THREAD

**Issue by agatho** [rxhan/RSCPGui#6]
Hi,

wenn ich versuche die Ladeeinstellungen zu übertragen kommt folgender Fehler

`Traceback (most recent call last):
  File "C:\RSCPGui\rscpguiframe.py", line 433, in bEMSUploadChangesOnClick
    for idlePeriod in self._data_ems['EMS_GET_IDLE_PERIODS']['EMS_IDLE_PERIOD']:
  File "C:\RSCPGui\e3dc\_rscp_dto.py", line 104, in __getitem__
    raise AttributeError()
AttributeError`

Aktuelle Git Version mit Python 3.9.1
certifi==2020.12.5
chardet==4.0.0
idna==2.10
influxdb==5.3.1
msgpack==1.0.2
numpy==1.20.0
paho-mqtt==1.5.1
Pillow==8.1.0
py3rijndael==0.3.3
python-dateutil==2.8.1
pytz==2021.1
requests==2.25.1
six==1.15.0
urllib3==1.26.3
websocket-client==0.57.0
wxPython==4.1.1

Viele Grüße

**Comment by rxhan** [comment]
Ich kann das Problem nicht nachstellen.
