### ISSUE TITLE
Installation auf RaspberryPi

### ISSUE THREAD

**Issue by smartboart** [rxhan/RSCPGui#7]
Hallo, hat das Programm schon mal jemand unter Linux auf einem Raspi oder einer anderen Platform laufen als Windows?
Probiere es gerade auf einem Raspi unter Linux laufen zu lassen.

**Comment by smartboart** [comment]
ok, das programm lässt sich schonmal ohne Fehler mit  python3 main.py starten. Kann das Tool auch ohne Desktop Linux Version bedient werden oder ist Desktop zwingend nötig?

**Comment by rxhan** [comment]
Hallo, ohne Desktop kann das Programm auch verwendet werden, jedoch nur für automatisierte Exportaufgaben. Dazu ist es aber notwendig vorher eine Konfigurationsdatei zu erstellen, dass kann man mit etwas Kentniss natürlich einfach in der ini machen, aber es geht einfacher wenn man einen Desktopclient hat auf dem man diese vorkonfigurieren kann. Die typische Verwendung auf dem Raspi wäre dann eben die automatische Exportfunktion nach z.B. MQTT, CSV, JSON oder Influx (aktueller Commit).

**Comment by smartboart** [comment]
Hallo, danke für die Info! Installiere gerade ne Desktop Version auf meinem Testsystem nach. Gute Idee mit der Datei...
Wegen der MQTT Funktionalität möchte ich das auch machen. Unter Windows hat das Prima geklappt , alle sates waren im iobroker verfügbar. Das Programm könnte neben bei auf einen meiner Server / Raspi laufen. Ohne desktop...
Noch ne Frage...lassen sich die Schaltbaren Funktionen auch per MQTT ansteuern?

**Comment by rxhan** [comment]
"Noch ne Frage...lassen sich die Schaltbaren Funktionen auch per MQTT ansteuern?"

Im Moment noch nicht, arbeite daran aktuell. In einem Test klappt das bereits für die Ladeleistung. Es wird dann so sein, dass das Feld, welches man setzen möchte auch für den Export angewählt sein muss, und man über den dort eingestellten Pfad dann mit dem Zusatz "/SET" jeweils im Topic den Wert setzen kann.

**Comment by smartboart** [comment]
Hallo,
danke für die Antwort... Dann werde ich auf jeden Fall mal regelmäßig nach Neuerungen schauen. Danke für das klasse Tool. Der Wahnsinn was man alles damit auslsesen kann.

**Comment by smartboart** [comment]
Noch ne kurze Frage , wie rufe ich die Gui im Deskopeiner Linux Installation auf?

**Comment by rxhan** [comment]
Ganz normal mit python3 main.py, wenn keine Gui startet ist wxPython nicht richtig installiert. Sollte aber auch im Log angezeigt werden. Dafür kann dann das logging auf die Console oder in eine Datei geleitet werden. -f logfile oder --logconsole 
mit -v DEBUG können dann alle Meldungen ausgegeben werden, dass ist aber recht viel, es reicht daher meist INFO oder WARNING. Fehlendes wxPython wird eine Warning generieren. Wenn das fehlt startet das Programm nur im Consolenmodus.

**Comment by smartboart** [comment]
Hi, hatte jetzt ne ganze Weile mit wxPython gekämft. Hoffe es ist nun richtig installiert. wen ich nun im Desktop das Terminal öffne und python3 main.py eintrag kommt folgende Meldung. Hast dueine Idee dazu?

Traceback (most recent call last):
  File "main.py", line 78, in <module>
    app.InitLocale()
AttributeError: 'App' object has no attribute 'InitLocale'

**Comment by smartboart** [comment]
Ok, mit der pre9 release hat es geklappt...hatte es mit dem Master Branch zuerst versucht...

**Comment by smartboart** [comment]
So, musste das Programm im Raspi Debian mehrmals starten bis es richtig lief. Wenn es läuft dann läuft es gut.

Python 3.7.3 habe ich in Betrieb. 
Habe sogar noch mal im Testsystem ein jungfreuliches image neu aufgesetzt, gleich mit Desktop. 
![grafik](https://user-images.githubusercontent.com/38385805/111550392-4947bf80-877e-11eb-95ce-bf005a6a4a1a.png)
getestet mit SD und HDD.

Alle Installationen liefen fehlerfrei. Laufffähig war in meinen Tests nur RSCPGui-pre9. 
Hier musste aber das tool auch diverse mal neu gestartet werden bis alles lief. Die anderen starteten erst garnicht.
Ist dir das bekannt? 
 Die Eingabekonfiguration bleibt auch nicht gespeichert. Beim Neustart muss alles wieder eingegeben werden.

Hast du das auch mal unter Linux getestet?  Hast ja  den Hinweis stehen, dass es nur unter Windows getestet wurde... 

Danke für deine Unterstützung.

**Comment by rxhan** [comment]
Hallo, tatsächlich hatte ich bislang nur die Konsolenvariante in Linux getestet. Die GUI wurde in einem Mac mal getestet, dass ging wohl. Dass der aktuelle Master solche Probleme macht ist mir noch nicht bekannt, danke sehr!
Ich werde mir wohl mal ein Linux-Testsystem aufbauen.
Der mqtt-Pfad kann angepasst werden, entweder über einen Knoten, dann für alle Unterknoten und deren Attribute oder je Attribut einzeln. Dazu ist das Feld Bezeichner gedacht.

**Comment by rxhan** [comment]
So habe ein Debian frisch aufgesetzt und folgende Befehle ausgeführt:
```
sudo apt-get install git python3-dev libgtk-3-dev libpulse-dev python3-venv wheel
git clone https://github.com/rxhan/RSCPGui
cd RSCPGui
python3 -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt 
python3 main.py
```
Also den Master verwendet.

Die Installation von wxPython hat sehr lange gedauert knapp über einer Stunde. Das Programm startet normal, nur "Daten auswählen" macht einen Fehler und es gibt GTK-Critical-Fehler. Ansonsten ist das erstaunlich schnell, unter Windows erscheint es mir langsamer. Ein paar Felder werden ungünstig angezeigt / sind zu groß oder zu klein oder zu gedrungen, oder werden vom Fenster überdeckt. Ich hab jetzt aber auch GTK-3 verwendet.

Ich habe mal einen Testbranch angelegt, in dem die aktuelle Entwicklung ist, in dieser Funktioniert das Fenster. Vorher muss noch einmal `pip3 install -r requirements` gemacht werden, da ein neues Modul (telegram) benötigt wird. Das ist für Benachrichtigungen gedacht.

**Comment by rxhan** [comment]
In dem testin3 Branch ist es auch möglich die MQTT-Werte zurückzuspielen. Dazu gibt es eine neue Option "Werteänderung zulassen".

**Comment by smartboart** [comment]
Super vielen Dank... So gibt es wieder wss zu testen., deine installations routine weicht etwas von meiner ab. Vlt. Lag es dann daran dass diverser branch Versionen bei mir  nicht liefen.. . Werde ich heute abend mal nachvollziehen.. Ich berichte..Fragen kommen bestimmt auch noch...😉

**Comment by smartboart** [comment]
ok, super! Mit der Installationsroutine läuft es wirklich prima. Auch die Konfigdaten werden nun gespeichert. 
die Master habe ich aber immer noch nicht zum laufen bekommen. startet nicht. Die pre9 aber schon..die testin branch konnte ich nicht finden.

Was mir aufgefallen ist, wenn der mqtt Broker neu gestartet wird, nimmt das tool nicht automatisch das Senden der Daten wieder auf. Esmuss einmal Beenden und starten betätigt werden. Manchmal geht das tool auch einfach zu wenn man den button betätigt. Vlt. liegt es ja auch an der pre 9 oder mein testsystem  Raspi 3 1GB ist einfach zu schwach auf der brust. Auf dem Raspi 4 mit 8 GB Ram Produktivsystem lasse ich es morgen mal laufen, eventuell macht das nochmal den unterschied.

**Comment by smartboart** [comment]
Ok, wie vermutet läuft es auf dem 4GB System nochmaldeutlich besser, hier funktioniert nun auch die Master branch.

**Comment by smartboart** [comment]
Ok, ich mache das issue zu, da das Thema Installation auf Linux RPI ja wunderbar läuft. Unterthemen wie Auflösung und Button Funktionen mache ich ein separates issue auf. Das Thema mit der Auflösung  habe ich ja Systemübergreifend.
