### ISSUE TITLE
saving settings throws error

### ISSUE THREAD

**Issue by DrNoD-hash** [rxhan/RSCPGui#8]
Wenn ich Benutzername / Passwort speichern will kommt dieser Fehler:

Traceback (most recent call last):
  File "rscpguiframe.py", line 1353, in bSaveClick
  File "rscpguiframe.py", line 2002, in saveConfig
  File "rscpguiframe.py", line 1996, in refreshConfig
  File "configparser.py", line 960, in __getitem__
KeyError: 'Export'

Nutze die Windows exe Datei

**Comment by mccrossen** [comment]
Als Workaround kann man im selben Verzeichnis wie die exe eine "rscpe3dc.conf.ini" erstellen mit folgendem Inhalt:
`[Login]

username=mye3dportalusername

password=mypassword

rscppassword=myrscppassword

address=192.168.xxx.yyy

seriennummer=S10-xxxxxxxxxxxx`

So habe ich mit temporär die Einstellungen manuell gesichert. 

@rxhan wäre eine Default-ini-Datei mit allen Einstellungen sinnvoll? Könnte ich als PullRequest zuarbeiten?

**Comment by rxhan** [comment]
Mein Ziel ist eigentlich, dass die Konfigurationsdatei vom Programm geschrieben wird. Dann kommt man bei Bedarf weiterhin mit einer executable aus.
